name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8,3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install -r test/requirements.txt
        coverage run -m pytest --junitxml=coverage-reports/coverage.xml

    #- name: Generate reports
    #  run: |
    #    coverage report
    #    coverage xml -o coverage-reports/coverage.xml
    #    coverage html

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  package:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: create package
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build
        python -m build

    - name: create package
      run: |
        pip install --user --upgrade setuptools wheel pkutils
        python setup.py sdist bdist_wheel

    - name: Update Github Page
      run: |
        mkdir public
        PACKAGE_VER=$(cat VERSION)
        cat >public/index.md <<EOL
        ## Python Package Index

        Page provides py Index for TestHelper
    
        [test_helper-${PACKAGE_VER}](git+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY#egg=test_helper-$PACKAGE_VER)
        EOL

    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE }}
        release_name: ${{ env.RELEASE }}
        body: |
          Changes in this Release
        draft: false
        prerelease: false
